In [1]:
import numpy as np
import time

In [2]:
# CONSTANTS
NO_METERS_P = 108
NO_POLES_P = 117
NO_METERS_C = 7172
NO_POLES_C = 6550

In [12]:
# ask user whether cap360 or phase1
#          whether preprocessing or not

In [279]:
data_file = np.loadtxt('cap360.txt', dtype=np.int32)
#data_file = np.loadtxt('phase1.txt', dtype=np.int32)

In [135]:
# Create an adjacency matrix of poles and meters
Adj_pm = np.zeros((NO_POLES_P, NO_METERS_P))
# Create an adjacency list for each pole
poles = [[] for i in range(NO_POLES_P)]
# Create an adjacency list for each meter
meters = [[] for i in range(NO_METERS_P)]


In [280]:
# Create an adjacency matrix of poles and meters
Adj_pm = np.zeros((NO_POLES_C, NO_METERS_C))
# Create an adjacency list for each pole
poles = [[] for i in range(NO_POLES_C)]
# Create an adjacency list for each meter
meters = [[] for i in range(NO_METERS_C)]


In [281]:
for x in data_file:
    if (x[1]-1 < 0):
        print("sime")
        print(x)
    x[0] -= 1 # Converting to 0-index
    x[1] -= 1
    Adj_pm[x[1]][x[0]] = 1
    meters[x[0]].append(x[1])
    poles[x[1]].append(x[0])

In [282]:
start_time = time.time()
sorted_array = np.argsort([len(x) for x in poles])[::-1]
# Create an empty for covered meters
cov_meters = np.zeros(NO_METERS_C)
# list of covered meters
list_cov_meters = []
# list of covering poles
list_cov_poles = []
j = 0
#while (np.any(cov_meters == 0)):
for j in range(len(sorted_array)):
    best_pole = sorted_array[j] # best pole by length
    list_cov_poles.append(best_pole)
    for x in (poles[best_pole]):
        cov_meters[x] += 1
        #if x not in list_cov_meters:
         #   list_cov_meters.append(x)
    #j += 1
    # Clean up
    for i in range(0, len(list_cov_poles), 1): # for each already selected pole(sp)
        if (i >= len(list_cov_poles)):
            break
        sp = list_cov_poles[i]
        cleanable = True
        for x in (poles[sp]):
            if ((cov_meters[x] - 1) == 0):
                cleanable = False
                break
        if (cleanable):
            list_cov_poles.remove(sp)
            #print("\nremoving ", sp)
            for x in (poles[sp]):
                cov_meters[x] -= 1
                #print(x, "   ", cov_meters[x])
           #print("----------------------")
print((time.time() - start_time))
print(len(list_cov_poles))
print(list_cov_poles)

14.186894178390503
636
[3616, 4436, 3857, 3220, 4993, 4295, 5700, 3622, 3710, 3945, 4209, 1878, 2451, 2656, 6190, 4040, 6252, 3947, 3332, 3968, 3936, 2471, 4471, 2518, 2911, 6062, 1997, 3836, 5953, 6377, 6241, 6096, 4705, 6362, 2949, 5962, 4283, 4411, 5183, 3021, 3079, 4567, 3349, 4531, 5847, 4965, 1778, 2239, 6048, 4751, 4144, 2972, 2886, 6225, 4700, 4946, 2586, 1792, 2232, 4834, 2494, 5385, 5762, 3073, 4389, 1892, 6461, 2775, 4615, 4420, 2893, 5160, 3632, 2043, 5310, 4880, 1550, 1433, 3588, 2148, 4091, 3757, 1545, 4444, 3208, 3278, 4758, 1944, 5464, 2199, 5484, 4875, 1317, 2296, 5860, 4967, 3898, 1205, 3595, 3823, 5251, 3963, 5673, 5562, 6182, 2553, 6422, 4344, 6320, 1464, 2971, 6032, 1732, 2188, 4570, 5202, 1100, 5468, 1211, 1281, 5929, 1363, 6141, 4264, 771, 2138, 5329, 1323, 2624, 5564, 2079, 5662, 3371, 2604, 4787, 1153, 1481, 4899, 1041, 5023, 2785, 3762, 1622, 1239, 1487, 3209, 2013, 2554, 3859, 5242, 4656, 2498, 1397, 4301, 3434, 5620, 4089, 4084, 2221, 5020, 5751, 4605, 2191,

In [153]:
%%time 
for i in range(8000):
    x = (Adj_pm[:, np.argsort(np.sum(Adj_pm, axis=0))].sum(axis=0))


KeyboardInterrupt: 

### Matrix based solution

In [248]:
data_file = np.loadtxt('cap360.txt', dtype=np.int32)
# Create a meters x poles matrix
Adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
# another modifiable matrix 
Mod_adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
for x in data_file:
    if (x[1]-1 < 0):
        print("sime")
        print(x)
    x[0] -= 1 # Converting to 0-index
    x[1] -= 1
    Adj_pm[x[0]][x[1]] = 1
    Mod_adj_pm[x[0]][x[1]] = 1

In [251]:
st = time.time()
Adj_pm[:, np.argsort(np.sum(Adj_pm, axis=0))]
print(time.time() - st)

1.0008959770202637


In [180]:
x = Adj_pm[:, np.argsort(np.sum(Adj_pm, axis=0))]

In [207]:
a = np.argsort(np.sum(Adj_pm, axis = 0))[::-1]

In [197]:
a[0]

3524

In [212]:
l = []

In [213]:
l.append(int(x) for x in np.argwhere(Adj_pm[:, a[0]] == 1))

In [214]:
l

[<generator object <genexpr> at 0x1158edd58>]

In [268]:
data_file = np.loadtxt('cap360.txt', dtype=np.int32)
# Create a meters x poles matrix
Adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
# another modifiable matrix 
Mod_adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
for x in data_file:
    if (x[1]-1 < 0):
        print("sime")
        print(x)
    x[0] -= 1 # Converting to 0-index
    x[1] -= 1
    Adj_pm[x[0]][x[1]] = 1
    Mod_adj_pm[x[0]][x[1]] = 1

start_time = time.time()
# Create an empty for covered meters
cov_meters = np.zeros(NO_METERS_C)
# list of covered meters
list_cov_meters = []
# list of covering poles
list_cov_poles = []
j = 0
indices = np.argsort(np.sum(Mod_adj_pm, axis = 0))[::-1]
while (np.any(cov_meters == 0)):
    # get sorting indices
    #indices = np.argsort(np.sum(Mod_adj_pm, axis = 0))[::-1]
    # add the best pole (indices[0])
    list_cov_poles.append(indices[j])
    #print(indices[0],"pole added")
    # find the corresponding column in the matrix
    x = Mod_adj_pm[:, indices[j]]
    j += 1
    # find the meters covered by this pole and add to overall covered meters
    # and set the corresponding row of the meter to zero
    met_poles = np.argwhere(x == 1) # orders of 10-4
    for met_idx in met_poles:
        cov_meters[int(met_idx)] += 1
        #Mod_adj_pm[met_idx, :] = 0
    # Clean up
    #st = time.time()
    for i in range(0, len(list_cov_poles)): # for each already selected pole(sp)
        if (i >= len(list_cov_poles)):
            break
        sp = list_cov_poles[i]
        cleanable = True
        meters_by_sp = np.argwhere(Adj_pm[:, sp] == 1) # meters covered by sp
        #print(meters_by_sp)
        for x in (meters_by_sp):
            if ((cov_meters[int(x)] - 1) == 0):
                cleanable = False
                break
        if (cleanable):
            list_cov_poles.remove(sp)
            print("\nremoving ", sp)
            for x in (meters_by_sp):
                cov_meters[int(x)] -= 1
                #print(x, "   ", cov_meters[x])
    #print(time.time()-st)
    
    #print(cov_meters)
    print(np.sum(cov_meters != 0))
print((time.time() - start_time))
print(len(list_cov_poles))
#print(list_cov_poles)

57
114
126
129
130

removing  3524

removing  3393
141

removing  3504
141
145
168

removing  3879
168

removing  3845
170

removing  3895
179
181
235
243

removing  3416
244

removing  3394
244

removing  3507
244

removing  3503
244

removing  4075

removing  3894
249

removing  3505
249
251

removing  3965
251

removing  3921
251
260
264

removing  3502
264

removing  3506
264

removing  3525
269
308

removing  3617
308

removing  3395
308
309

removing  3944
309

removing  3501
309

removing  3526
311

removing  3456
311

removing  3331
311
321

removing  3306
323

removing  3363
323

removing  3417
323

removing  3966
323

removing  3801

removing  3500
323
333

removing  3705
334
384

removing  3753
384
387
388

removing  3802
388

removing  4111
394

removing  4031
394

removing  4195
394
444

removing  4155
446

removing  4121
446

removing  3285
446

removing  3704
446

removing  4032
446
455

removing  4082
462
466

removing  3935
476
479
480

removing  2545
480

removing  42

2381

removing  4754
2381
2383

removing  6312
2385

removing  3347
2386

removing  3905

removing  3684
2388

removing  4225
2388

removing  4352
2388

removing  2830
2388

removing  6208
2388
2389

removing  2131
2390

removing  3329
2390

removing  3726
2390
2391
2395

removing  3071
2395

removing  6313
2395

removing  4390
2395

removing  2592
2396
2404

removing  4623
2404
2405

removing  4711
2406

removing  5532
2416
2417

removing  4701
2417

removing  4368
2417

removing  2591
2417

removing  5140
2418
2421

removing  5139
2421
2423

removing  2361
2423
2432

removing  3145
2432
2434

removing  2954
2435

removing  5288

removing  5293
2435

removing  3946
2435
2436
2437

removing  4304

removing  4354
2437

removing  6353
2437

removing  4112
2440

removing  3309
2440

removing  4639
2440
2445
2453

removing  2420
2453
2465
2468

removing  5606
2475

removing  3537
2475

removing  4976
2475

removing  4764
2475

removing  3344
2477

removing  4227
2477

removing  4251

remov


removing  5677

removing  5311
3123

removing  4512
3123

removing  4141
3123

removing  4139
3123

removing  4939
3123

removing  4529
3123

removing  5322
3123

removing  4536
3123

removing  1853
3123

removing  4959
3124

removing  4370
3124
3126
3127

removing  4428
3127
3128

removing  3775

removing  3701
3128

removing  2678
3128

removing  2823

removing  2589
3129

removing  4048
3129

removing  4357
3129

removing  3694
3129

removing  5427
3131

removing  4744
3131

removing  4568
3131

removing  4860
3131

removing  4375
3132

removing  2111
3134

removing  6157
3134

removing  6054
3137

removing  3039

removing  2907
3139
3142

removing  2958
3143

removing  3067
3143

removing  3064
3143

removing  2529
3143

removing  6117
3143

removing  2870
3145

removing  5718
3145

removing  3082
3145

removing  6336

removing  6355
3148
3149

removing  6148
3150

removing  2336
3160

removing  2831
3160
3164

removing  5702
3164

removing  6378
3164

removing  2315
3164

removin

3777
3781
3793
3811

removing  5334
3811

removing  5349
3811

removing  4557
3811

removing  4530
3811
3816

removing  2241
3816

removing  5837
3817
3818

removing  5831
3818

removing  5651
3818

removing  1902
3818

removing  1102
3818

removing  804
3819

removing  5841
3819

removing  2707
3819

removing  2621
3819

removing  5416
3826

removing  5511
3826

removing  5652
3826

removing  5599
3830

removing  2819
3834

removing  4379
3834

removing  2374
3834

removing  4793
3834

removing  1684
3834

removing  4878
3835

removing  2912
3835
3869
3894

removing  3072
3894

removing  5439
3894

removing  2557
3894

removing  6301
3894

removing  4385
3894

removing  4290
3894

removing  5725
3894

removing  1138
3894

removing  6168
3895

removing  2579
3895

removing  2750
3895
3903

removing  4479
3903

removing  1871
3903

removing  2096
3904
3905
3907

removing  1990
3907

removing  5482

removing  5382
3907

removing  1457
3909

removing  4836
3909

removing  1813
3909

remov


removing  1786
4340
4345

removing  5723
4345

removing  6384
4345

removing  2250
4346

removing  4243
4347

removing  4171
4350

removing  1365
4350

removing  1890
4350

removing  6404
4350

removing  1385
4362

removing  1361
4362

removing  1325
4362

removing  6387
4364

removing  4503
4364

removing  2787
4364

removing  1583
4364

removing  2234
4364

removing  1115
4364
4365

removing  6431
4368

removing  6439
4368

removing  1352
4369

removing  6371
4369

removing  4621
4369

removing  2734
4369

removing  4494
4369

removing  4495
4369

removing  2108
4369

removing  4687
4369

removing  4427
4369

removing  1567
4369

removing  1105
4371
4401
4402

removing  4730
4402
4434

removing  2733
4434

removing  2212
4441

removing  4885
4441

removing  2252
4441

removing  4371
4441

removing  6397
4441

removing  1514
4441

removing  4539
4441

removing  4086
4443

removing  4697
4443

removing  4419
4443

removing  6440
4443
4445

removing  1601
4445

removing  2913
4445

rem


removing  1066
4720

removing  5433

removing  5536
4720

removing  1974
4720

removing  5372
4720

removing  2200
4720

removing  1067
4720

removing  5483
4721
4727

removing  1456
4727

removing  4969
4727
4734

removing  4811
4734
4737

removing  5513

removing  5515
4740

removing  5985
4740

removing  5899
4742

removing  4929
4742

removing  4169
4742
4749

removing  4986
4749

removing  4935
4749

removing  5989
4750

removing  3383
4750
4752

removing  1333
4752

removing  4214
4752

removing  5992
4752

removing  1306
4752

removing  2605
4753

removing  3235
4755

removing  5930
4756
4758

removing  2103
4758

removing  1857

removing  1934

removing  1781
4758

removing  2508
4758

removing  2106
4758

removing  5938
4758

removing  4945
4758

removing  2532
4758

removing  3268
4758

removing  1298
4760

removing  2225

removing  2386
4760

removing  5825
4760

removing  2161
4767

removing  3159
4767

removing  4968
4767

removing  5946
4767

removing  4977
4767

removin


removing  1461
5083

removing  5886
5083

removing  1142
5083

removing  2120
5083

removing  1304
5083

removing  5722
5083

removing  4331
5083

removing  5022
5083

removing  4837
5083

removing  2261
5083

removing  2415
5083

removing  5027
5083

removing  2193
5083

removing  4542
5084

removing  2265
5084

removing  4933
5084

removing  5869
5084

removing  3252
5084

removing  4336
5084
5085

removing  1816
5089

removing  5426
5089

removing  2370
5089

removing  5421
5089

removing  6083

removing  6149
5089

removing  2099
5089

removing  1185
5090

removing  5905
5090
5091

removing  1172
5092

removing  1313
5092

removing  1789
5093

removing  2174
5093

removing  2320
5094
5103
5105

removing  1434
5105
5108

removing  5330
5108
5111

removing  2122
5111

removing  1400
5114

removing  1633
5114

removing  1517
5114

removing  1339
5114

removing  2215
5114

removing  3783
5114

removing  1680
5114

removing  5960
5114

removing  3150
5115

removing  5412
5115

removing

5319

removing  1793
5319

removing  5628
5319

removing  4002
5319

removing  1542
5319

removing  6126
5319

removing  1572
5319

removing  2760
5319

removing  3430
5319

removing  1653
5319

removing  4308
5319

removing  1184
5320

removing  1187
5320

removing  6150
5320

removing  3601

removing  3860
5328

removing  1256
5328

removing  1535
5328

removing  1139
5328

removing  745
5328

removing  4151
5328

removing  4426

removing  4043
5328

removing  4124
5328

removing  1634
5328
5329

removing  2269
5329

removing  1472
5329

removing  3736
5329

removing  1681
5329

removing  1263
5329
5355

removing  775
5356

removing  3301
5356

removing  1627
5356

removing  5062
5356

removing  4960
5356

removing  3300
5356

removing  2601
5356

removing  4052
5356

removing  5006
5357

removing  4073
5357

removing  4953
5357

removing  4972
5357

removing  1677
5357

removing  2243
5357

removing  4842
5361

removing  4104
5361

removing  5861
5361

removing  1271
5361

removing 


removing  1958
5526

removing  971
5527

removing  3478
5535

removing  2718
5535

removing  2033
5536

removing  3533
5536

removing  4163
5536

removing  4029
5536

removing  4165
5536

removing  3245
5536

removing  2207
5536
5537

removing  1441
5537

removing  2176
5537

removing  723
5538

removing  4051
5538

removing  3511
5538

removing  5766
5538

removing  5399
5538

removing  1554
5538

removing  1377
5538

removing  4667
5540

removing  953
5540

removing  4588
5540
5541

removing  2895
5543

removing  1625

removing  1593
5543

removing  1421
5543

removing  4501
5543

removing  3999
5543

removing  1585
5543

removing  2196
5547
5571

removing  4587
5571

removing  1488
5571

removing  1494
5571

removing  1193
5571

removing  1215
5571
5572

removing  4358
5573

removing  5391

removing  5204
5573

removing  1922
5573
5581

removing  2040
5581

removing  5172
5581

removing  1744
5583
5586

removing  5245
5586

removing  1435
5586

removing  3194
5586

removing  5308
5


removing  5645
5827

removing  1846
5827

removing  2367
5827

removing  5681
5827

removing  1599
5827

removing  5783
5827

removing  724
5827
5828

removing  5407
5828

removing  5428
5828

removing  5228
5828

removing  5307
5828

removing  1942
5828

removing  1116
5833

removing  4987

removing  5073
5833

removing  5111
5833

removing  5123
5833

removing  5128
5833
5834

removing  5180
5834

removing  975
5834

removing  5215
5834

removing  5254
5834

removing  5262
5834

removing  5270
5834

removing  5272
5834

removing  1904
5834

removing  939
5834

removing  2366
5834

removing  5378
5834

removing  2358
5834

removing  5854
5834

removing  5829
5834

removing  5882
5834

removing  5889
5834
5856

removing  2208
5856
5858

removing  6278
5858

removing  525
5859

removing  1767
5861
5863

removing  1762
5863

removing  6423
5863

removing  6481
5863

removing  6472
5863

removing  6473
5863

removing  6474
5863

removing  1674
5863

removing  1666
5863

removing  1742
58


removing  1025
6042

removing  3674
6042

removing  1030
6042

removing  5053
6042

removing  1011
6042

removing  5379
6042
6044

removing  1194

removing  1296

removing  1354
6045
6046

removing  3603
6046

removing  4204

removing  3672
6046
6047
6049

removing  1159
6049

removing  4113
6050

removing  4320
6050

removing  1167
6050

removing  2440
6050

removing  4442
6050

removing  1137

removing  1136
6050

removing  4117
6050

removing  4328
6053

removing  4552
6053

removing  4590
6053

removing  3985
6053

removing  3956
6053

removing  3902
6053

removing  4725
6053

removing  4763
6053

removing  4767
6053

removing  4770
6053

removing  4772
6053

removing  4774
6053

removing  4609
6053

removing  2437
6053

removing  2381
6053

removing  1929
6053

removing  5505
6053

removing  1979
6057
6077

removing  1756
6077

removing  821
6077

removing  5457
6078

removing  3188
6078

removing  5451
6079

removing  5469
6081
6083
6084

removing  5524
6084

removing  2353
6084


removing  3372
6234

removing  3373
6234

removing  5230
6234

removing  1552
6234

removing  350
6234

removing  357
6234
6235

removing  3106
6235

removing  2915
6235

removing  2660

removing  2919
6235

removing  2835
6235

removing  1657
6235

removing  2278
6235

removing  2300
6235

removing  1523
6235

removing  2292
6236

removing  2356
6236

removing  2423
6236

removing  2401
6236

removing  2421

removing  2413
6236

removing  2652
6236

removing  2509
6236

removing  2134
6236

removing  2548
6236

removing  2543
6236

removing  2495
6236

removing  2564
6236

removing  2609
6236
6238

removing  2669
6238

removing  2699
6238

removing  2742
6238

removing  2804
6238

removing  2822
6238

removing  2836
6238

removing  2834
6238

removing  1226
6238

removing  3388
6240

removing  3592
6240

removing  479
6240

removing  1992
6240

removing  4635
6240

removing  4679
6240

removing  3593
6240

removing  4708
6240

removing  1076
6240
6242

removing  1580
6243

removing  


removing  540
6441

removing  867
6443

removing  6218
6443

removing  3429
6444

removing  283
6444

removing  5470
6446

removing  5554
6446
6447

removing  6309
6447

removing  6214
6448

removing  639
6448

removing  6268
6449

removing  1921
6449
6450

removing  1233
6450

removing  534
6450

removing  6119
6450

removing  564
6450

removing  6257
6450

removing  1632
6450

removing  330
6450

removing  888
6451

removing  660
6451

removing  311
6451

removing  369
6452

removing  2322
6452
6453

removing  3120
6454

removing  3433

removing  3629
6455

removing  862
6455

removing  5388
6455

removing  6346
6455

removing  5920
6455

removing  489
6455

removing  6100
6455

removing  3732
6455

removing  2276
6456

removing  6195
6456

removing  3746

removing  4280
6458

removing  6086
6458

removing  668
6458

removing  474
6458

removing  3436
6460
6461

removing  3426
6461

removing  1072
6461

removing  3699
6461

removing  393
6461

removing  5919
6461

removing  392
6461


removing  5637
6655

removing  602
6658

removing  618
6658

removing  143
6660

removing  5559
6663

removing  141
6663

removing  139
6663

removing  768
6663

removing  778
6663

removing  2034
6663
6664

removing  566
6664
6665

removing  2050
6665

removing  1980
6665
6666

removing  136

removing  134
6666
6667

removing  607
6667

removing  1869
6667

removing  587
6667

removing  588
6667
6668
6671

removing  1861
6671

removing  606
6671
6672

removing  123
6672
6674

removing  5911
6674

removing  5629
6674

removing  836
6674

removing  6448
6675

removing  6256
6676

removing  6317
6676

removing  2268
6676
6686

removing  2262
6686

removing  2259
6686

removing  2258
6686
6687

removing  5943
6687
6690

removing  1826
6690

removing  674
6691

removing  164
6691

removing  5632
6691

removing  498
6691

removing  148
6691

removing  6217
6691
6692

removing  2218
6692

removing  2201
6692

removing  5977
6692
6693

removing  147
6693

removing  5707
6694

removing  2101


6897

removing  5602
6898
6899

removing  4958
6902

removing  5924
6904

removing  2112
6904

removing  5525
6904

removing  1106
6904

removing  4805
6904

removing  5493
6904

removing  4856
6904

removing  3606
6904

removing  1073
6904

removing  1668

removing  1817
6904

removing  740
6904

removing  845
6904

removing  4733
6904

removing  661
6904

removing  1093
6904

removing  5918
6904
6905

removing  3258
6905

removing  4458
6905

removing  1868
6905

removing  695
6905
6906

removing  2085
6907
6908
6910

removing  2084
6910

removing  1887
6910

removing  4321
6910
6911

removing  648
6911

removing  1837
6911

removing  1875
6912

removing  1214
6912

removing  5447
6912

removing  3105
6912

removing  1750
6912

removing  6345
6912

removing  552
6912
6914

removing  556
6915

removing  910
6915

removing  3321
6916

removing  3360
6916

removing  6538
6916

removing  5480
6916

removing  898
6917

removing  326
6917

removing  6492
6917

removing  345
6917

removing 

7109

removing  6544
7109

removing  3024
7109

removing  782
7109

removing  48
7109
7110
7112
7113
7114
7115

removing  211
7115

removing  6105
7116

removing  574
7117

removing  6174
7117

removing  216
7117

removing  204
7117
7118

removing  219
7119

removing  799
7119

removing  5431

removing  5366
7119

removing  922
7119

removing  295

removing  324
7119
7120

removing  6
7120

removing  6516
7120

removing  64
7120
7121

removing  3355
7121
7122

removing  286
7122

removing  253
7122

removing  834
7122
7123

removing  825
7123
7125
7126

removing  61
7127
7128
7129

removing  58
7129

removing  57
7129
7130

removing  54
7130

removing  63
7130

removing  49
7130

removing  17

removing  7
7130

removing  6546
7131

removing  104
7131
7133

removing  3872
7133

removing  3675
7133
7134

removing  3269
7134

removing  6548
7134

removing  3611
7135

removing  3443
7136

removing  3190
7136

removing  3135
7136

removing  3061
7136

removing  3214
7136

removing  3011
713

In [20]:
# Greedy algorithm
data_file = np.loadtxt('cap360.txt', dtype=np.int32)
# Create a meters x poles matrix
Adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
# another modifiable matrix 
Mod_adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
for x in data_file:
    x[0] -= 1 # Converting to 0-index
    x[1] -= 1
    Adj_pm[x[0]][x[1]] = 1
    Mod_adj_pm[x[0]][x[1]] = 1

start_time = time.time()
# Create an zero vector for covered meters (assigned 0 for uncovered meters)
cov_meters = np.zeros(NO_METERS_C)
# list of covered meters
list_cov_meters = []
# list of covering poles
list_cov_poles = []
total = 0
while (np.any(cov_meters == 0)):
    # get sorting indices
    #indices = np.argsort(np.sum(Mod_adj_pm, axis = 0))[::-1]
    indices = np.argmax(np.sum(Mod_adj_pm, axis = 0))
    #print("best pole is ", indices)
    # add the best pole (indices)
    list_cov_poles.append(indices)
    # find the corresponding column in the matrix
    x = Adj_pm[:, indices]
    # find the meters covered by this pole and add to overall covered meters
    # and set the corresponding row of the meter to zero
    met_poles = [int(m) for m in np.argwhere(x == 1)] # time in orders of 10-4
    cov_meters[met_poles] += 1
    Mod_adj_pm[met_poles, :] = 0
    #for met_idx in met_poles:
        #cov_meters[int(met_idx)] += 1
        #Mod_adj_pm[met_idx, :] = 0
    # Clean up
    #st = time.time()
    clean_up_indices = []
    for i in range(0, len(list_cov_poles), 10): # for each already selected pole(sp)
        #if (i >= len(list_cov_poles)):
        #    break
        sp = list_cov_poles[i]
        #cleanable = True
        #print(meters_by_sp)
        #for x in (meters_by_sp):
        #    if ((cov_meters[int(x)] - 1) == 0):
        #        cleanable = False
        #        break
        meters_by_sp = [int(m) for m in np.argwhere(Adj_pm[:, sp] == 1)] # meters covered by sp
        if (np.any((cov_meters[meters_by_sp]-1) == 0) == False):
            clean_up_indices.append(i)
            #list_cov_poles.remove(sp)
            print("\nremoving ", sp)
            cov_meters[meters_by_sp] -= 1
            #for x in (meters_by_sp):
                #cov_meters[int(x)] -= 1
                #print(x, "   ", cov_meters[x])
    st = time.time()
    for j in sorted(clean_up_indices, reverse=True):
        del list_cov_poles[j]
    total += (time.time()-st)
    #print(time.time()-st)
    #print(cov_meters)
    #print(np.sum(cov_meters != 0))
print((time.time() - start_time))
print(len(list_cov_poles))
print(total)
#print(list_cov_poles)

20.79549789428711
625
0.003467559814453125


In [109]:
# Modified Greedy algorithm
data_file = np.loadtxt('cap360.txt', dtype=np.int32)
# Create a meters x poles matrix
Adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
# another modifiable matrix 
Mod_adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
for x in data_file:
    x[0] -= 1 # Converting to 0-index
    x[1] -= 1
    Adj_pm[x[0]][x[1]] = 1
    Mod_adj_pm[x[0]][x[1]] = 1

start_time = time.time()
# Create an zero vector for covered meters (assigned 0 for uncovered meters)
cov_meters = np.zeros(NO_METERS_C)
# list of covered meters
list_cov_meters = []
# list of covering poles
list_cov_poles = []
total = 0
hard_to_cover = np.where(np.sum(Mod_adj_pm, axis = 1) == np.min(np.sum(Mod_adj_pm, axis = 1)))
while (np.any(cov_meters == 0)):
    # get sorting indices
    #indices = np.argsort(np.sum(Mod_adj_pm, axis = 0))[::-1]
    # scores = [Mod_adj_pm[hard_to_cover].sum(axis=0) > 0] * Mod_adj_pm.sum(axis=0) # Score 1
    scores = [Mod_adj_pm[hard_to_cover].sum(axis=0)] * Mod_adj_pm.sum(axis=0) # Score 2
    if (np.any(scores > 0)):
        indices = np.argmax(scores)
    else: # if all hard to cover meters are covered
        indices = np.argmax(np.sum(Mod_adj_pm, axis = 0))
    #print("best pole is ", indices)
    # add the best pole (indices)
    list_cov_poles.append(indices)
    # find the corresponding column in the matrix
    x = Adj_pm[:, indices]
    # find the meters covered by this pole and add to overall covered meters
    # and set the corresponding row of the meter to zero
    met_poles = [int(m) for m in np.argwhere(x == 1)] # time in orders of 10-4
    cov_meters[met_poles] += 1
    Mod_adj_pm[met_poles, :] = 0
    #for met_idx in met_poles:
        #cov_meters[int(met_idx)] += 1
        #Mod_adj_pm[met_idx, :] = 0
    # Clean up
    #st = time.time()
    clean_up_indices = []
    for i in range(0, len(list_cov_poles)): # for each already selected pole(sp)
        #if (i >= len(list_cov_poles)):
        #    break
        sp = list_cov_poles[i]
        #cleanable = True
        #print(meters_by_sp)
        #for x in (meters_by_sp):
        #    if ((cov_meters[int(x)] - 1) == 0):
        #        cleanable = False
        #        break
        meters_by_sp = [int(m) for m in np.argwhere(Adj_pm[:, sp] == 1)] # meters covered by sp
        if (np.any((cov_meters[meters_by_sp]-1) == 0) == False):
            clean_up_indices.append(i)
            #list_cov_poles.remove(sp)
            print("\nremoving ", sp)
            cov_meters[meters_by_sp] -= 1
            #for x in (meters_by_sp):
                #cov_meters[int(x)] -= 1
                #print(x, "   ", cov_meters[x])
    st = time.time()
    for j in sorted(clean_up_indices, reverse=True):
        del list_cov_poles[j]
    total += (time.time()-st)
    #print(time.time()-st)
    #print(cov_meters)
    print(np.sum(cov_meters != 0))
print((time.time() - start_time))
print(len(list_cov_poles))
print(total)
#print(list_cov_poles)

14
20
23
26
30
38
46
53
60
63
69
75
78
83
88
93
95
97
99
101
105
107
109
111
113
117
119
121
125
127
131
135
139
141
145
147
149
151
153
157
161
163
166
169
172
175
178
181
184
187
190
193
196
199
201
203
205
207
209
211
213
215
217
219
221
223
225
227
229
231
233
234
235
236
237
238
239
240
297
354
408
459
509
559
608
657
705
753
799
845
891
937
982
1026
1070
1114
1157
1200
1243
1285
1327
1369
1411
1452
1493
1534
1575
1615
1654
1693
1732
1771
1810
1848
1886
1924
1961
1998
2035
2072
2108
2144
2180
2215
2250
2285
2320
2355
2390
2425
2460
2494
2528
2562
2596
2629
2662
2695
2727
2759
2791
2823
2854
2885
2916
2947
2977
3007
3037
3067
3097
3126
3155
3184
3213
3241
3269
3297
3325
3353
3381
3408
3435
3462
3488
3514
3540
3566
3591
3616
3641
3666
3691
3716
3741
3766
3790
3814
3838
3862
3886
3910
3934
3957
3980
4003
4026
4049
4072
4095
4118
4141
4164
4186
4208
4230
4252
4274
4296
4318
4340
4361
4382
4403
4424
4445
4466
4487
4507
4527
4547
4567
4587
4607
4627
4647
4667
4687
4706
4725
4744
4763
47

In [24]:
np.min(np.sum(Adj_pm, axis = 1))

2.0

In [32]:
hard_to_cover = np.where(np.sum(Adj_pm, axis = 1) == np.min(np.sum(Adj_pm, axis = 1)))

In [36]:
hard_to_cover

(array([   0,    1,    4,    6,   44,   46,   47,   49,   50,   51,   53,
          54,   56,   90,   94,   95,   96,  101,  108,  115,  116,  119,
         120,  179,  186,  200,  201,  204,  219,  224,  247,  284,  289,
         298,  306,  320,  325,  356,  358,  362,  363,  365,  405,  423,
         427,  527,  688,  789,  806,  823,  885,  894,  904,  938, 1037,
        1174, 1223, 1377, 1413, 1542, 2352, 2395, 2408, 2439, 2498, 2521,
        2631, 2663, 2869, 2988, 3177, 3266, 3271, 3495, 3587, 3691, 3736,
        3941, 4035, 4620, 4958, 5001, 5246, 5575, 5635, 6259, 6471, 6579,
        6696, 6708, 6779, 6784, 6870, 6871, 6873, 6875, 6876, 6894, 7098,
        7105, 7107, 7108, 7110]),)

In [45]:
if (np.any(Adj_pm[hard_to_cover, i])):
    

SyntaxError: invalid syntax (<ipython-input-45-36ef17c5d5c2>, line 1)

In [55]:
Adj_pm[hard_to_cover, 62]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]])

In [59]:
Adj_pm.sum(axis = 0)

array([2., 2., 3., ..., 4., 2., 2.])

In [61]:
[Adj_pm[hard_to_cover].sum(axis=0) > 0] * Adj_pm.sum(axis=0)

array([[2., 2., 3., ..., 0., 2., 2.]])

In [53]:
np.argmax(np.sum(Adj_pm[hard_to_cover], axis =0))

62

In [57]:
(Adj_pm[hard_to_cover, 0].sum() > 0)    

True

In [98]:
np.where(np.sum(Adj_pm, axis = 1) == 2)

(array([   0,    1,    4,    6,   44,   46,   47,   49,   50,   51,   53,
          54,   56,   90,   94,   95,   96,  101,  108,  115,  116,  119,
         120,  179,  186,  200,  201,  204,  219,  224,  247,  284,  289,
         298,  306,  320,  325,  356,  358,  362,  363,  365,  405,  423,
         427,  527,  688,  789,  806,  823,  885,  894,  904,  938, 1037,
        1174, 1223, 1377, 1413, 1542, 2352, 2395, 2408, 2439, 2498, 2521,
        2631, 2663, 2869, 2988, 3177, 3266, 3271, 3495, 3587, 3691, 3736,
        3941, 4035, 4620, 4958, 5001, 5246, 5575, 5635, 6259, 6471, 6579,
        6696, 6708, 6779, 6784, 6870, 6871, 6873, 6875, 6876, 6894, 7098,
        7105, 7107, 7108, 7110]),)

In [99]:
np.argwhere(np.sum(Adj_pm, axis = 1) == 2)[0]

array([0])

In [103]:
Adj_pm


array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [104]:
np.argwhere(Adj_pm[0, :] == 1)

array([[1]])

In [ ]:
# Preprocessing included algorithm
data_file = np.loadtxt('cap360.txt', dtype=np.int32)
# Create a meters x poles matrix
Adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
# another modifiable matrix 
Mod_adj_pm = np.zeros((NO_METERS_C, NO_POLES_C))
for x in data_file:
    x[0] -= 1 # Converting to 0-index
    x[1] -= 1
    Adj_pm[x[0]][x[1]] = 1
    Mod_adj_pm[x[0]][x[1]] = 1

start_time = time.time()
# Create an zero vector for covered meters (assigned 0 for uncovered meters)
cov_meters = np.zeros(NO_METERS_C)
# list of covered meters
list_cov_meters = []
# list of covering poles
list_cov_poles = []
total = 0
k = 1
while (np.any(cov_meters == 0)):
    # get sorting indices
    #indices = np.argsort(np.sum(Mod_adj_pm, axis = 0))[::-1]
    # Preprocessing (k times):
    for i in range(k):
        # 1. Removing singleton rows
        singleton_rows = [int(x) for x in np.argwhere(np.sum(Mod_adj_pm, axis = 1) == 1)]
        # Add the pole corresponding to the first singleton row
        if singleton_rows: # if there is atleast one singleton row
            print("Singleton pole added!")
            pole = int(np.argwhere(Mod_adj_pm[singleton_rows[0], :] == 1))
            list_cov_poles.append(pole)        
            x = Adj_pm[:, pole]
            met_poles = [int(m) for m in np.argwhere(x == 1)] # time in orders of 10-4
            cov_meters[met_poles] += 1
            Mod_adj_pm[:, pole] = 0 
    
    indices = np.argmax(np.sum(Mod_adj_pm, axis = 0))
    #print("best pole is ", indices)
    # add the best pole (indices)
    list_cov_poles.append(indices)
    # find the corresponding column in the matrix
    x = Adj_pm[:, indices]
    # find the meters covered by this pole and add to overall covered meters
    # and set the corresponding row of the meter to zero
    met_poles = [int(m) for m in np.argwhere(x == 1)] # time in orders of 10-4
    cov_meters[met_poles] += 1
    Mod_adj_pm[met_poles, :] = 0
    #for met_idx in met_poles:
        #cov_meters[int(met_idx)] += 1
        #Mod_adj_pm[met_idx, :] = 0
    # Clean up
    #st = time.time()
    clean_up_indices = []
    for i in range(0, len(list_cov_poles), 10): # for each already selected pole(sp)
        #if (i >= len(list_cov_poles)):
        #    break
        sp = list_cov_poles[i]
        #cleanable = True
        #print(meters_by_sp)
        #for x in (meters_by_sp):
        #    if ((cov_meters[int(x)] - 1) == 0):
        #        cleanable = False
        #        break
        meters_by_sp = [int(m) for m in np.argwhere(Adj_pm[:, sp] == 1)] # meters covered by sp
        if (np.any((cov_meters[meters_by_sp]-1) == 0) == False):
            clean_up_indices.append(i)
            #list_cov_poles.remove(sp)
            print("\nremoving ", sp)
            cov_meters[meters_by_sp] -= 1
            #for x in (meters_by_sp):
                #cov_meters[int(x)] -= 1
                #print(x, "   ", cov_meters[x])
    st = time.time()
    for j in sorted(clean_up_indices, reverse=True):
        del list_cov_poles[j]
    total += (time.time()-st)
    #print(time.time()-st)
    #print(cov_meters)
    print(np.sum(cov_meters != 0))
print((time.time() - start_time))
print(len(list_cov_poles))
print(total)
#print(list_cov_poles)

Singleton pole added!
57
Singleton pole added!
114
Singleton pole added!
168
Singleton pole added!
219
Singleton pole added!
269
Singleton pole added!
319
Singleton pole added!
368
Singleton pole added!
417
Singleton pole added!
465
Singleton pole added!
513
Singleton pole added!
559
Singleton pole added!
605
Singleton pole added!
651
Singleton pole added!
697
Singleton pole added!
742
Singleton pole added!
786
Singleton pole added!
830
Singleton pole added!
874
Singleton pole added!
917
Singleton pole added!
960
Singleton pole added!
1003
Singleton pole added!
1045
Singleton pole added!
1087
Singleton pole added!
1129
Singleton pole added!
1171
Singleton pole added!
1212
Singleton pole added!
1253
Singleton pole added!
1294
Singleton pole added!
1335
Singleton pole added!
1375
Singleton pole added!
1414
Singleton pole added!
1453
Singleton pole added!
1492
Singleton pole added!
1531
Singleton pole added!
1570
Singleton pole added!
1608
Singleton pole added!
1646
Singleton pole added!
